### ISSUE TITLE
Unable to load BranchNet/build/tracer/tracer.so: dlopen failed: cannot locate symbol "_ZSt4cerr" referenced by "BranchNet/build/tracer/tracer.so"

### ISSUE THREAD

**Issue by Jinghui-Z** [siavashzk/BranchNet#10]
Why do I prompt 'Unable to load BranchNet/build/tracer/tracer.so: dlopen failed: cannot locate symbol "_ZSt4cerr" referenced by "BranchNet/build/tracer/tracer.so"' when using './bin/create_branch_traces. py'

**Comment by Jinghui-Z** [comment]
I have successfully run Pin and run './bin/build_tracer. py'

**Comment by Jinghui-Z** [comment]
May I have your email? I have some questions to ask you

**Comment by siavashzk** [comment]
Sorry, forgot to reply. My email is siavash.zangeneh@utexas.edu. Although I can't promise to have time to debug infrastructure issues (like scripts not working). Happy to discuss the paper.

**Comment by Jinghui-Z** [comment]
it's ok, I resolved this bug by downloading pin version 3.11, but I seem to have encountered some issues in creating the dataset. The source code is as follows:
for br_pc in hard_brs:
        print('processing branch {}'.format(hex(br_pc)))
        #find indicies of hard branches
        trace_br_indices = np.argwhere(pcs == br_pc).squeeze(axis=1)
        fptr.create_dataset(
            'br_indices_{}'.format(hex(br_pc)),
            data=trace_br_indices,
            compression='gzip',
            compression_opts=9,
        )
        
        
May I ask if there will be any issues with my modifications like this：
for br_pc in hard_brs:
        print('processing branch {}'.format(hex(br_pc)))
        #find indicies of hard branches
        trace_br_indices = np.argwhere((pcs & pc_mask) == (br_pc & pc_mask)).squeeze(axis=1)
        fptr.create_dataset(
            'br_indices_{}'.format(hex(br_pc)),
            data=trace_br_indices,
            compression='gzip',
            compression_opts=9,
        )

**Comment by siavashzk** [comment]
I don’t know what your use case is, but if you need to do a partial pc match in your experiments, sure!

**Comment by Silent12rt** [comment]
> it's ok, I resolved this bug by downloading pin version 3.11, but I seem to have encountered some issues in creating the dataset. The source code is as follows: for br_pc in hard_brs: print('processing branch {}'.format(hex(br_pc))) #find indicies of hard branches trace_br_indices = np.argwhere(pcs == br_pc).squeeze(axis=1) fptr.create_dataset( 'br_indices_{}'.format(hex(br_pc)), data=trace_br_indices, compression='gzip', compression_opts=9, )
> 
> May I ask if there will be any issues with my modifications like this： for br_pc in hard_brs: print('processing branch {}'.format(hex(br_pc))) #find indicies of hard branches trace_br_indices = np.argwhere((pcs & pc_mask) == (br_pc & pc_mask)).squeeze(axis=1) fptr.create_dataset( 'br_indices_{}'.format(hex(br_pc)), data=trace_br_indices, compression='gzip', compression_opts=9, )

I am currently working with Pin 3.11, but I noticed that the package I downloaded does not include PinPlay. Could you please let me know how to obtain a Pin 3.11 release with PinPlay support?
