### ISSUE TITLE
 Intel Pin Tool configuration issues.

### ISSUE THREAD

**Issue by szywmx** [siavashzk/BranchNet#12]
Hello, I am a college student, and our final assignment for computer architecture is to replicate a research paper. I would like to replicate your paper, but I'm facing numerous file configuration issues while using the Intel Pin Tool. Could the author provide the configured files with the generated results and send them to me? The deadline is in only 10 days, and I hope the author can fulfill my request. Thank you very much (T_T(crying)) @siavashzk

**Comment by xzx0805** [comment]
@szywmx Did the author reply to you? If not, maybe we can add a contact number to communicate? I have also been troubled by the pintool environment for several days recently. Maybe you can contact him by E-mail. Thank you.

**Comment by siavashzk** [comment]
Hi, I'm not a student any more and I don't have any of those files. But part of being a college student is struggling with tools and getting them to work.

I ran my code with CentOs7 and the pintool that came with pinplay support (it's a different binary release from the normal pin). I tested pin 3.5 or 3.11.

If those versions are too old and don't work with your OS anymore, you should try getting the newest version, and adapting the code to be compatible with a modern version of Intel Pin and Ubuntu.
