### ISSUE TITLE
Question about file benchmarks_example.yaml

### ISSUE THREAD

**Issue by chnjstyj** [siavashzk/BranchNet#13]
I'm not sure what content should fill in the yaml file. I have already built the tracer and installed the spec2017 content.
You said 
"If you cannot use this script, but want to use the rest of the scripts, that is fine as long as you follow the same naming conventions when you create the branch traces yourself."
and I found simpoints of spec2017 in https://github.com/UT-LCA/Scalability-Phase-Simpoint-of-SPEC-CPU2017.
Is that meaning I can use the link's release to move on experiments?
I tried to fill the file like 
![QQ截图20240329165612](https://github.com/siavashzk/BranchNet/assets/52889312/1bf71c9c-b232-4dc3-b73d-098bf16a2e8d)
But the command failed and told me 
![QQ截图20240329165728](https://github.com/siavashzk/BranchNet/assets/52889312/0e75372a-9585-401e-b2f8-474de6c62590)
Thank you.

**Comment by siavashzk** [comment]
Hi, the software released along the BranchNet paper are provided as is, and I don't have time to support the tools provided. If you have questions about the ideas behind the paper, I'll be happy to discuss the paper.

It seems like the script is working fine in terms of producing the command line to run the branch tracer pintool. There must be something incompatible (e.g., the simpoint pinball you downloaded from the other repo may only be compatible with some pin versions, the pintool I provided in this repo may only be compatible with some older pin versions). You should debug the problem on your own. A good starting point would be to test if you can run any example pintools, then see if you can run those simple pintools on the SPEC simpoints you found, and then move to trying to adapt the BranchNet pintool for your environment.

**Comment by chnjstyj** [comment]
Thank you !
