### ISSUE TITLE
g++: error /tracer.o: No such file or directory 

### ISSUE THREAD

**Issue by Vtecbest** [siavashzk/BranchNet#2]
Hello, I have a question here. When I run ./bin/build_tracer.py, an error occurs as the topic shows. I believe I installed Pin Tools, so may I know how to solve this? Looking forward to your reply.

**Comment by Vtecbest** [comment]
Also, I think in this command
"build_dir_path = os.path.dirname(os.path.abspath(__file__)) + '/../build/tage'"
build folder is missing.  Please let me know if I misunderstood. Thanks.

**Comment by siavashzk** [comment]
Hello,

Can you copy the full log of the build here?

Have you tried building a PIN tool independent of BranchNet to see if it works? PIN comes with many sample examples.

What version of PIN do you have, and have you set the environment variable PIN_ROOT to point to the PIN directory?

**Comment by Vtecbest** [comment]
Thanks for your reply. I set my PIN_ROOT now, but now it said:''pinplay.H: no such file or directory". I think it's the version issue because I installed the latest version(3.18). Also, now there's no 3.5 or 3.11 version on the Intel web. Do you have any suggestions?

**Comment by siavashzk** [comment]
Looks like I was sloppy when documenting the dependencies. I used the "PinPlay" version of the PIN tools. See [here](https://software.intel.com/content/www/us/en/develop/articles/program-recordreplay-toolkit.html) for download links. 

Note that the PinPlay aspect is not really relevant for BranchNet, just something useful for my infrastructure of running SPEC benchmarks. If you don't need the PinPlay functionality, you can modify the tracer not to use pinplay by removing a few lines of code in tracer.cpp and use a makefile provided by your version of PIN.

**Comment by Vtecbest** [comment]
Thanks for your links. I think to run your program correctly, Simpoint and Pinballs is also necessary, right?

**Comment by siavashzk** [comment]
Well, to run all the scripts as-is, you would need to use Pinballs. But the real reason I open-sourced this project was to provide the BranchNet model definition in Pytorch for reproducibility of the paper, which is independent of the tracing infrastructure. For example, you could replace pinballs with any other mechanism that makes the most sense in your environment.

**Comment by Vtecbest** [comment]
OK, I get it. Thanks again for your patience.

**Comment by siavashzk** [comment]
No problem, feel free to re-open the issue if you have other questions.
