### ISSUE TITLE
Error while creating branch traces

### ISSUE THREAD

**Issue by arnavw96** [siavashzk/BranchNet#6]
Hey! I'm trying to reproduce your results but facing the following issue when I try to run the create_branch_traces.py file:

 ./bin/create_branch_traces.py
Traceback (most recent call last):
  File "./bin/create_branch_traces.py", line 52, in <module>
    main()
  File "./bin/create_branch_traces.py", line 46, in main
    cmds.append(get_run_cmd(pinball_path, trace_path))
  File "./bin/create_branch_traces.py", line 12, in get_run_cmd
    pin_root = os.environ['PIN_ROOT']
  File "/usr/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'PIN_ROOT'

I have followed the previously required steps. Could you help how to resolve this issue?

**Comment by siavashzk** [comment]
Hi, installing PIN requires you set the environment variable PIN_ROOT to the absolute path of wherever you installed PIN.

For example, you can execute this in the command-line:
`export PIN_ROOT=/path/to/your/pin/download`

If you don't want to do this everytime, you can add it in your .bashrc, .bash_profile or other equivalent files in your Linux distribution

**Comment by arnavw96** [comment]
Thanks, that worked! But now I'm getting the following error:

Traceback (most recent call last):
  File "./bin/create_branch_traces.py", line 52, in <module>
    main()
  File "./bin/create_branch_traces.py", line 46, in main
    cmds.append(get_run_cmd(pinball_path, trace_path))
  File "./bin/create_branch_traces.py", line 13, in get_run_cmd
    assert os.path.exists(TRACER_PINTOOL_PATH)
AssertionError

How can I get the tracer.so file?

**Comment by siavashzk** [comment]
Seems like you haven't build the tracer pintool.

Did this step succeed?
```./bin/build_tracer.py```

**Comment by arnavw96** [comment]
When I try to run that, the following error pops up:

make[1]: *** No rule to make target '/home/arnavwadhwa/BranchNet/pin-3.25-98650-g8f6168173-gcc-linux/extras/pinplay//lib/intel64/libpinplay.a', needed by 'obj-intel64//tracer.so'.  Stop.
make[1]: *** Waiting for unfinished jobs....
tracer.cpp:19:21: fatal error: pinplay.H: No such file or directory
 #include "pinplay.H"
                     ^
compilation terminated.
makefile.rules:199: recipe for target 'obj-intel64//tracer.o' failed
make[1]: *** [obj-intel64//tracer.o] Error 1
make[1]: Leaving directory '/home/arnavwadhwa/BranchNet/src/tracer'
makefile.rules:121: recipe for target 'all' failed
make: *** [all] Error 2

Am I missing something here? Sorry I'm new to comp arch so might be missing something and would appreciate the help!

**Comment by siavashzk** [comment]
I think you have the wrong pin version. I forgot to specify in the readme that my code uses the Pinplay version of pin. You can download it from here. I have tested pin 3.11.

https://www.intel.com/content/www/us/en/developer/articles/tool/program-recordreplay-toolkit.html

Actually, these are not comp arch issues per se. You are going through the environment setup phase :) I'll try to help with these kind of issues as much as I can. But I cannot solve all the problems, and you may have modify the code to adapt it to your environment.

**Comment by arnavw96** [comment]
Thank you!
