### ISSUE TITLE
Hardware dependencies?

### ISSUE THREAD

**Issue by arnavw96** [siavashzk/BranchNet#7]
From the perspective of testing the TAGE + CNN's misprediction rates, are there any specific **hardware dependencies** -- like a custom processor, required to run this codebase?
I have a Linux system and have installed the following dependencies mentioned in the readme:

> Linux (I mainly use CentOS)
> 
> Python packages, with the versions that I've used:
> 
> Package         Version
> --------------- -------
> h5py            2.10.0
> matplotlib      3.1.1
> numpy           1.17.2
> PyYAML          5.1.2
> torch           1.3.0
> torchvision     0.4.1
> 
> Intel Pin Tool for generating branch traces (I've tested with 3.5 and 3.11)
> 
> cmake3 and make

**Comment by siavashzk** [comment]
You would need a GPU to run CNN training and evaluation steps. You can technically run it on a CPU for small-scale experiments but it would be too slow.

Any GPU would be fine as long as Pytorch can recognize and use the GPU.

**Comment by arnavw96** [comment]
Thanks!
