### ISSUE TITLE
MPKI calculation

### ISSUE THREAD

**Issue by Vtecbest** [siavashzk/BranchNet#8]
Hi, I noticed your instrumentation function in your tracer only records the PC which isn't non-branch, then how did you calculate the following MPKI? I think non-branch instructions should also be considered in this metric.![image](https://github.com/siavashzk/BranchNet/assets/72300677/c16e5041-a024-454b-b471-a89264b211a2)

**Comment by siavashzk** [comment]
Hey, in my case, I knew that each trace was generated from a 200M instruction checkpoint, so I implicitly assumed 200M instruction per trace in the MPKI calculations.

MPKI of a trace = (number of mispredictions) / 200M * 1000

In the case of multiple simpoints, you would weight the number of mispredictions by their corresponding simpoint weights

**Comment by Vtecbest** [comment]
Oh, I see, Thanks!
